from pathlib import Path

path = Path("src/app/pages/inventario/inventario.page.scss")
text = path.read_text(encoding="utf-8")
marker = "  .total-icon ion-icon {\r\n    font-size: 30px;\r\n    color: #ffffff;\r\n  }\r\n\r\n"
insert = (
    "  .dashboard-cards {\r\n"
    "    display: grid;\r\n"
    "    gap: 16px;\r\n"
    "    padding: 0 20px;\r\n"
    "    grid-template-columns: repeat(2, minmax(0, 1fr));\r\n"
    "    margin-top: 16px;\r\n"
    "  }\r\n\r\n"
    "  .device-status-card,\r\n"
    "  .recent-activity-card {\r\n"
    "    background: #ffffff;\r\n"
    "    border-radius: 24px;\r\n"
    "    border: 1px solid #e0e3e5;\r\n"
    "    padding: 18px;\r\n"
    "    box-shadow: 0 10px 30px rgba(15, 23, 42, 0.04);\r\n"
    "  }\r\n\r\n"
    "  .card-header-row {\r\n"
    "    display: flex;\r\n"
    "    align-items: center;\r\n"
    "    justify-content: space-between;\r\n"
    "    gap: 12px;\r\n"
    "    margin-bottom: 18px;\r\n"
    "  }\r\n\r\n"
    "  .card-header-row h2 {\r\n"
    "    margin: 0;\r\n"
    "    font-size: 17px;\r\n"
    "    color: #0f172a;\r\n"
    "  }\r\n\r\n"
    "  .status-pill,\r\n"
    "  .activity-note {\r\n"
    "    font-size: 12px;\r\n"
    "    font-weight: 700;\r\n"
    "    text-transform: uppercase;\r\n"
    "    letter-spacing: 0.04em;\r\n"
    "    padding: 7px 12px;\r\n"
    "    border-radius: 999px;\r\n"
    "  }\r\n\r\n"
    "  .status-pill.online {\r\n"
    "    background: rgba(56, 189, 248, 0.16);\r\n"
    "    color: #0ea5e9;\r\n"
    "  }\r\n\r\n"
    "  .activity-note {\r\n"
    "    color: #64748b;\r\n"
    "    background: #f8fafc;\r\n"
    "  }\r\n\r\n"
    "  .device-status-list {\r\n"
    "    display: grid;\r\n"
    "    gap: 12px;\r\n"
    "    margin-bottom: 16px;\r\n"
    "  }\r\n\r\n"
    "  .device-status-item {\r\n"
    "    display: flex;\r\n"
    "    justify-content: space-between;\r\n"
    "    align-items: center;\r\n"
    "    padding: 14px 16px;\r\n"
    "    border-radius: 16px;\r\n"
    "    background: #f8fafc;\r\n"
    "  }\r\n\r\n"
    "  .device-status-item span {\r\n"
    "    font-size: 12px;\r\n"
    "    color: #64748b;\r\n"
    "  }\r\n\r\n"
    "  .device-status-item strong {\r\n"
    "    font-size: 14px;\r\n"
    "    color: #0f172a;\r\n"
    "  }\r\n\r\n"
    "  .device-status-footer {\r\n"
    "    display: flex;\r\n"
    "    justify-content: space-between;\r\n"
    "    gap: 12px;\r\n"
    "    padding: 12px 16px;\r\n"
    "    border-radius: 16px;\r\n"
    "    background: #f8fafc;\r\n"
    "    font-size: 13px;\r\n"
    "    color: #334155;\r\n"
    "  }\r\n\r\n"
    "  .activity-list {\r\n"
    "    display: grid;\r\n"
    "    gap: 12px;\r\n"
    "  }\r\n\r\n"
    "  .activity-item {\r\n"
    "    display: grid;\r\n"
    "    grid-template-columns: auto 1fr auto;\r\n"
    "    align-items: center;\r\n"
    "    gap: 12px;\r\n"
    "    padding: 14px 16px;\r\n"
    "    border-radius: 18px;\r\n"
    "    background: #f8fafc;\r\n"
    "  }\r\n\r\n"
    "  .activity-icon {\r\n"
    "    width: 40px;\r\n"
    "    height: 40px;\r\n"
    "    display: grid;\r\n"
    "    place-items: center;\r\n"
    "    border-radius: 14px;\r\n"
    "    background: rgba(59, 130, 246, 0.12);\r\n"
    "    color: #2563eb;\r\n"
    "  }\r\n\r\n"
    "  .activity-icon ion-icon {\r\n"
    "    font-size: 18px;\r\n"
    "  }\r\n\r\n"
    "  .activity-content h3 {\r\n"
    "    margin: 0;\r\n"
    "    font-size: 14px;\r\n"
    "    color: #0f172a;\r\n"
    "  }\r\n\r\n"
    "  .activity-content p {\r\n"
    "    margin: 4px 0 0;\r\n"
    "    font-size: 12px;\r\n"
    "    color: #64748b;\r\n"
    "  }\r\n\r\n"
    "  .activity-time {\r\n"
    "    font-size: 12px;\r\n"
    "    color: #64748b;\r\n"
    "    text-align: right;\r\n"
    "    white-space: nowrap;\r\n"
    "  }\r\n\r\n"
    "  .activity-item.activity-success .activity-icon {\r\n"
    "    background: rgba(16, 185, 129, 0.16);\r\n"
    "    color: #059669;\r\n"
    "  }\r\n\r\n"
    "  .activity-item.activity-warning .activity-icon {\r\n"
    "    background: rgba(251, 191, 36, 0.16);\r\n"
    "    color: #ca8a04;\r\n"
    "  }\r\n\r\n"
    "  .activity-item.activity-primary .activity-icon {\r\n"
    "    background: rgba(59, 130, 246, 0.16);\r\n"
    "    color: #2563eb;\r\n"
    "  }\r\n\r\n"
    "  @media (max-width: 920px) {\r\n"
    "    .dashboard-cards {\r\n"
    "      grid-template-columns: 1fr;\r\n"
    "    }\r\n"
    "  }\r\n\r\n"
    "  @media (max-width: 640px) {\r\n"
    "    .dashboard-cards,\r\n"
    "    .total-products-card,\r\n"
    "    .summary-card,\r\n"
    "    .status-card,\r\n"
    "    .expiring-products,\r\n"
    "    .inventory-chart,\r\n"
    "    .recipes-section {\r\n"
    "      padding: 0 16px;\r\n"
    "    }\r\n\r\n"
    "    .device-status-card,\r\n"
    "    .recent-activity-card,\r\n"
    "    .status-card,\r\n"
    "    .summary-card,\r\n"
    "    .total-products-card,\r\n"
    "    .expiring-products,\r\n"
    "    .inventory-chart,\r\n"
    "    .recipes-section {\r\n"
    "      border-radius: 20px;\r\n"
    "    }\r\n"
    "  }\r\n\r\n"
)

if marker not in text:
    raise SystemExit('marker not found')
path.write_text(text.replace(marker, marker + insert), encoding="utf-8")
print("inserted")
